language: node_js
node_js:
  - node
  - lts/*
install:
  - npm install -g codecov
cache:
  directories:
    - ~/.npm
before_script:
  - cd pvt71 && npm install -g npm@latest && npm install -g yarn && cd ..
script:
  - cd pvt71 && yarn && npx jest --ci --forceExit
  - codecov
